name = "posthog-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "raidcli.dev/ingest/*", zone_name = "raidcli.dev" },
  { pattern = "raidcli.dev/favicon.ico", zone_name = "raidcli.dev" },
]
